# Generated by Django 5.1.7 on 2025-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
